name: Third workflow
run-name: Third workflow
on: 
  workflow_dispatch:
jobs:
  tag-image:
    runs-on: ubuntu-latest
    steps:
      - id: commit
        uses: prompt/actions-commit-hash@v3
      - name: "Get commit's short, long, HASH SHA strings"
        env:    
          SHORT: ${{ steps.commit.outputs.short }}
          LONG: ${{ steps.commit.outputs.long }}
          HASH: ${{ steps.commit.outputs.hash }}
        run: echo "$SHORT"
        run: echo "$LONG"
        run: echo "$HASH"
