name: Third workflow
run-name: Third workflow
on: 
  workflow_dispatch:
jobs:
  tag-image:
    runs-on: ubuntu-latest
    steps:
    steps:
      - id: commit
        uses: prompt/actions-commit-hash@v3
