name: Third workflow
run-name: Third workflow
on: 
  workflow_dispatch:
jobs:
  tag-image:
    runs-on: ubuntu-latest
    steps:
      - id: commit
        uses: prompt/actions-commit-hash@v3
       - name: Build, tag, and push image to Amazon ECR
        env:    
          SHORT: ${{ steps.commit.outputs.short }}
        run: echo "$SHORT"
